src/CoreBundle/Entity/TblCurso.php
<?php

namespace CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * CoreBundle\Entity\TblCurso
 *
 * @ORM\Entity()
 * @ORM\Table(name="tbl_curso")
 */
class TblCurso
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    protected $duracion;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $f_inicio;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $f_termino;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \CoreBundle\Entity\TblCurso
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \CoreBundle\Entity\TblCurso
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set the value of duracion.
     *
     * @param string $duracion
     * @return \CoreBundle\Entity\TblCurso
     */
    public function setDuracion($duracion)
    {
        $this->duracion = $duracion;

        return $this;
    }

    /**
     * Get the value of duracion.
     *
     * @return string
     */
    public function getDuracion()
    {
        return $this->duracion;
    }

    /**
     * Set the value of f_inicio.
     *
     * @param \DateTime $f_inicio
     * @return \CoreBundle\Entity\TblCurso
     */
    public function setFInicio($f_inicio)
    {
        $this->f_inicio = $f_inicio;

        return $this;
    }

    /**
     * Get the value of f_inicio.
     *
     * @return \DateTime
     */
    public function getFInicio()
    {
        return $this->f_inicio;
    }

    /**
     * Set the value of f_termino.
     *
     * @param \DateTime $f_termino
     * @return \CoreBundle\Entity\TblCurso
     */
    public function setFIncio($f_termino)
    {
        $this->f_incio = $f_termino;

        return $this;
    }

    /**
     * Get the value of f_termino.
     *
     * @return \DateTime
     */
    public function getFTermino()
    {
        return $this->f_termino;
    }

    public function __sleep()
    {
        return array('id', 'nombre', 'duracion', 'f_inicio', 'f_termino');
    }
}

src/CoreBundle/Entity/TblEmpleado.php
<?php

namespace CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * CoreBundle\Entity\TblEmpleado
 *
 * @ORM\Entity()
 * @ORM\Table(name="tbl_empleado")
 */
class TblEmpleado
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    protected $curp;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    protected $puesto;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \CoreBundle\Entity\TblEmpleado
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \CoreBundle\Entity\TblEmpleado
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set the value of curp.
     *
     * @param string $curp
     * @return \CoreBundle\Entity\TblEmpleado
     */
    public function setCurp($curp)
    {
        $this->curp = $curp;

        return $this;
    }

    /**
     * Get the value of curp.
     *
     * @return string
     */
    public function getCurp()
    {
        return $this->curp;
    }

    /**
     * Set the value of puesto.
     *
     * @param string $puesto
     * @return \CoreBundle\Entity\TblEmpleado
     */
    public function setPuesto($puesto)
    {
        $this->puesto = $puesto;

        return $this;
    }

    /**
     * Get the value of puesto.
     *
     * @return string
     */
    public function getPuesto()
    {
        return $this->puesto;
    }

    public function __sleep()
    {
        return array('id', 'nombre', 'curp', 'puesto');
    }
}

src/CoreBundle/Entity/TblEstacion.php
<?php

namespace CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * CoreBundle\Entity\TblEstacion
 *
 * @ORM\Entity()
 * @ORM\Table(name="tbl_estacion")
 */
class TblEstacion
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $r_social;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $rfc;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $r_patronal;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $r_trabajador;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \CoreBundle\Entity\TblEstacion
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of r_social.
     *
     * @param string $r_social
     * @return \CoreBundle\Entity\TblEstacion
     */
    public function setRSocial($r_social)
    {
        $this->r_social = $r_social;

        return $this;
    }

    /**
     * Get the value of r_social.
     *
     * @return string
     */
    public function getRSocial()
    {
        return $this->r_social;
    }

    /**
     * Set the value of rfc.
     *
     * @param string $rfc
     * @return \CoreBundle\Entity\TblEstacion
     */
    public function setRfc($rfc)
    {
        $this->rfc = $rfc;

        return $this;
    }

    /**
     * Get the value of rfc.
     *
     * @return string
     */
    public function getRfc()
    {
        return $this->rfc;
    }

    /**
     * Set the value of r_patronal.
     *
     * @param string $r_patronal
     * @return \CoreBundle\Entity\TblEstacion
     */
    public function setRPatronal($r_patronal)
    {
        $this->r_patronal = $r_patronal;

        return $this;
    }

    /**
     * Get the value of r_patronal.
     *
     * @return string
     */
    public function getRPatronal()
    {
        return $this->r_patronal;
    }

    /**
     * Set the value of r_trabajador.
     *
     * @param string $r_trabajador
     * @return \CoreBundle\Entity\TblEstacion
     */
    public function setRTrabajador($r_trabajador)
    {
        $this->r_trabajador = $r_trabajador;

        return $this;
    }

    /**
     * Get the value of r_trabajador.
     *
     * @return string
     */
    public function getRTrabajador()
    {
        return $this->r_trabajador;
    }

    public function __sleep()
    {
        return array('id', 'r_social', 'rfc', 'r_patronal', 'r_trabajador');
    }
}

src/CoreBundle/Controller/DefaultController.php
<?php

namespace CoreBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        // replace this example code with whatever you need
        return $this->render('default/index.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.root_dir').'/..').DIRECTORY_SEPARATOR,
        ]);
    }
}

src/CoreBundle/Resources/views/Default/index.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{ asset('assets/ico/favicon.png') }}">

    <title>SPOT - Free Bootstrap 3 Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('assets/css/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/font-awesome.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                <a class="navbar-brand" href="#">STPS<i class="fa fa-certificate"></i></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="index.html.twig">INICIO</a></li>
                <li><a href="about.html">CAIDAS</a></li>
                <!--<li><a data-toggle="modal" data-target="#myModal" href="#myModal"><i class="fa fa-envelope-o"></i></a></li>-->
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>


<div class="container">
    <div class="row">
        <br><br>
        <div class="col-lg-12">
            <h1>DC3</h1>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Nombre del trabajor</th>
                    <th scope="col">Estación</th>
                    <th scope="col">Curso</th>
                    <th scope="col">Descarga</th>


                </tr>
                </thead>
                <tbody>
                {% for e in em  %}
                {% for es in est %}

                <tr>
                    <td>{{ e.nombre }}</td>

                    <td>{{ es.rSocial }}</td>

                    <td>

                            <select class="form-control" id="sel1">
                                {% for c in curso %}
                                <option>{{ c.nombre }}</option>
                                {% endfor %}
                            </select>

                    </td>

                    <td>
                        <a class="btn btn-default btn-cons m-t-10" href="{{ path('doc') }}" role="button"><i class="fa fa-download"></i> Descargar </a>
                    </td>
                </tr>

                {% endfor  %}
                {% endfor %}

                </tbody>
            </table>
        </div><!-- col-lg-12 -->
    </div>




<!-- FOOTER -->
<div id="f">
    <div class="container">
        <div class="row centered">


        </div><!-- row -->
    </div><!-- container -->
</div><!-- Footer -->


<!-- MODAL FOR CONTACT -->
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">contact us</h4>
            </div>
            <div class="modal-body">
                <div class="row centered">
                    <p>We are available 24/7, so don't hesitate to contact us.</p>
                    <p>
                        Somestreet Ave, 987<br/>
                        London, UK.<br/>
                        +44 8948-4343<br/>
                        hi@blacktie.co
                    </p>
                    <div id="mapwrap">
                        <iframe height="300" width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.es/maps?t=m&amp;ie=UTF8&amp;ll=52.752693,22.791016&amp;spn=67.34552,156.972656&amp;z=2&amp;output=embed"></iframe>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Save & Go</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
</body>
</html>

src/CoreBundle/Resources/views/Default/inicio.html.twig
{% extends('CoreBundle::layout.html.twig') %}

{% block body %}

    <h1>DC3</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Nombre del trabajor</th>
            <th scope="col">Estación</th>
            <th scope="col">Curso</th>
            <th scope="col">Descarga</th>


        </tr>
        </thead>
        <tbody>
        {% for e in em  %}
        {% for es in est %}

        <tr>
            <td>{{ e.nombre }}</td>

            <td>{{ es.rSocial }}</td>

            <td>
                <form action="" method="post" name="curso">
                <select class="form-control" id="curso" name="curso">
                    {% for c in curso %}
                        <option value="{{ c.id }}">{{ c.nombre }}</option>
                    {% endfor %}

                </select>
                </form>
            </td>

            <td>
                <a class="btn btn-default btn-cons m-t-10" href="{{ path('doc') }}" role="button"><i class="fa fa-download"></i> Descargar </a>
            </td>

        </tr>
        {% endfor  %}
        {% endfor %}

        </tbody>
    </table>
</div><!-- col-lg-12 -->
</div>


{% endblock %}

src/CoreBundle/Resources/views/Default/prueba.html.twig
{% extends('CoreBundle::layout.html.twig') %}

{% block body %}

    <h1>DC3</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Nombre del trabajor</th>
            <th scope="col">Estación</th>
            <th scope="col">Curso</th>
            <th scope="col">Descarga</th>


        </tr>
        </thead>
        <tbody>
        {% for e in em  %}
        {% for es in est %}

        <tr>
            <td>{{ e.nombre }}</td>

            <td>{{ es.rSocial }}</td>
            <form action="" method="post">
            <td>

                <select class="form-control" id="curso" name="curso">
                    {% for c in curso %}
                        <option value="{{ c.id }}">{{ c.nombre }}</option>
                    {% endfor %}
                </select>
            </td>

            <td>
                <a class="btn btn-default btn-cons m-t-10" href="{{ path('doc') }}" role="button"><i class="fa fa-download"></i> Descargar </a>
            </td>
            </form>
        </tr>
        {% endfor  %}
        {% endfor %}

        </tbody>
    </table>
</div><!-- col-lg-12 -->
</div>


{% endblock %}

src/CoreBundle/Resources/views/layout.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{ asset('assets/ico/favicon.png') }}">

    <title>STPS</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('assets/css/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/font-awesome.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                <a class="navbar-brand" href="#">STPS<i class="fa fa-certificate"></i></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="index.html.twig">INICIO</a></li>
                <li><a href="about.html">CAIDAS</a></li>
                <!--<li><a data-toggle="modal" data-target="#myModal" href="#myModal"><i class="fa fa-envelope-o"></i></a></li>-->
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>


<div class="container">
    <div class="row">
        <br><br>
        <div class="col-lg-12">
            {% block body %}
            {% endblock %}
        </div><!-- col-lg-12 -->
    </div>




<!-- FOOTER -->
    <div class="container">
        <div class="row text-center">
            © KreatSolutions - Derechos reservados.

        </div><!-- row -->
    </div><!-- container -->



<!-- MODAL FOR CONTACT -->
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">contact us</h4>
            </div>
            <div class="modal-body">
                <div class="row centered">
                    <p>We are available 24/7, so don't hesitate to contact us.</p>
                    <p>
                        Somestreet Ave, 987<br/>
                        London, UK.<br/>
                        +44 8948-4343<br/>
                        hi@blacktie.co
                    </p>
                    <div id="mapwrap">
                        <iframe height="300" width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.es/maps?t=m&amp;ie=UTF8&amp;ll=52.752693,22.791016&amp;spn=67.34552,156.972656&amp;z=2&amp;output=embed"></iframe>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Save & Go</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
</body>
</html>